### PR TITLE
Fixing execution model and making compatible with windows

### PR DESCRIPTION
**Pull request by rohitggarg**
I know this is huge, I tested it across windows on a msi and my macbook.
Just see if nothing breaks on linux because of my changes.

### CODE REVIEW

**Comment by rohitggarg** [comment]
This is 0.2.0 :)

**Comment by rohitggarg** [comment]
Hi,
Are you looking into this one?

Thanks,
RohitG

**Comment by rohitggarg** [comment]
Hi, Please look at it.. 
Waiting for your reply

**Comment by xfrr** [comment]
Please, update the doc if you don't mind, thanks :)

**Comment by rohitggarg** [comment]
Did you manage to check it on some linux server?

**Comment by rohitggarg** [comment]
I faced a difficulty, when I don't read the stderr but subscribe on linux, the process and will hang after some time. So I added a switch when doing Run call to keep it optional

**Pull request merged**
